# Generated by Django 5.2.1 on 2025-08-08 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockmovement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmovement',
            old_name='timestamp',
            new_name='movement_date',
        ),
    ]
